spring:
  h2:
    console:
      enabled: true
      path: /h2-console
#  datasource:
#    url: jdbc:h2:file:./data/reminderData;DB_CLOSE_ON_EXIT=FALSE;AUTO_SERVER=TRUE
#    driverClassName: org.h2.Driver
#    username: sa
#    password: password
#  jpa:
#    showSql: true
#    databasePlatform: org.hibernate.dialect.H2Dialect
#    hibernate:
#      ddlAuto: update
  kafka:
    bootstrapServers: pkc-p11xm.us-east-1.aws.confluent.cloud:9092
    properties:
      sasl:
        mechanism: PLAIN
        jaas:
          config: org.apache.kafka.common.security.plain.PlainLoginModule required username='5RCXVD2ERCLBVDMD' password='7TTfxDTHgbsBDYHNsweUVfou8svtadcwMRb7xZPc+33KCpKAMu6Bhzvdpku1uaLE';
      bootstrapServers: pkc-p11xm.us-east-1.aws.confluent.cloud:9092
      security:
        protocol: SASL_SSL
      session:
        timeout:
          ms: 45000
      basic:
        auth:
          credentials:
            source: USER_INFO
          user:
            info: "{{ SR_API_KEY }}:{{ SR_API_SECRET }}"
      schema:
        registry:
          url: https://psrc-lq2dm.us-east-2.aws.confluent.cloud
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

server:
  port: 8888

bezkoder:
  app:
    jwtSecret: ======================BezKoder=Spring===========================
    jwtExpirationMs: 3000000


logging:
  level:
    org:
      springframework:
        security: DEBUG